id: discord-user-feedback
namespace: app.htch.comms

variables:
  topic: "FeedbackSent"
  kafka_username: "nope"
  kafka_password: "nope"
  kafka_bootstrap_endpoint: "nope"

tasks:
  - id: ionToJSON
    type: io.kestra.plugin.serdes.json.JsonWriter
    newLine: true
    from: "{{ trigger.uri }}"

  - id: pause
    type: io.kestra.core.tasks.flows.Pause
    delay: PT1S

triggers:
  - id: kafka
    type: io.kestra.plugin.kafka.Trigger
    topic: "{{ vars.topic }}"
    # important! Without pollDuration, the trigger doesn't work
    pollDuration: PT20S
    groupId: "{{ flow.id }}"
    properties:
      bootstrap.servers: "{{ vars.kafka_bootstrap_endpoint }}"
      sasl.mechanism: "SCRAM-SHA-512"
      security.protocol: "SASL_SSL"
      auto.offset.reset: "earliest"
      sasl.jaas.config: |
        org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ vars.kafka_username }}" password="{{ vars.kafka_password }}";
    keyDeserializer: STRING
    valueDeserializer: JSON

taskDefaults:
  - type: io.kestra.core.tasks.flows.Flow
    values:
      wait: true
      transmitFailed: true
