name: Kestra CI/CD

on: [push]

jobs:
  # Start by validating all kestra resources
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy `app.htch.assets.comms` flows"
        uses: kestra-io/deploy-action@v0.14.0
        with:
          namespace: app.htch.comms
          directory: ./flows
          resource: flow
          server: ${{ secrets.KESTRA_HOST_MAIN }}
          user: ${{ secrets.KESTRA_USER_MAIN }}
          password: ${{ secrets.KESTRA_PASSWORD_MAIN }}
